//TASK INBOX
export const GET_TASK = "GET_TASK";
export const NEW_TASK = "NEW_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";

//CATEGORY
export const GET_CATEGORY = "GET_CATEGORY";
export const NEW_CATEGORY = "NEW_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

//PROJECTS
export const GET_PROJECTS = "GET_PROJECTS";
export const NEW_PROJECTS = "NEW_PROJECTS";
export const DELETE_PROJECTS = "DELETE_PROJECTS";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
